name: declare
description: "A lightweight, SwiftUI-inspired state management library for Flutter. Powered by State, ViewModel, and Published."
version: 1.0.0
homepage: https://github.com/siva-sankar-dev/declare.git
repository: https://github.com/siva-sankar-dev/declare.git
issue_tracker: https://github.com/siva-sankar-dev/declare/issues

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
